# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(770, 991)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkWorkingLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkWorkingLabel.sizePolicy().hasHeightForWidth())
        self.checkWorkingLabel.setSizePolicy(sizePolicy)
        self.checkWorkingLabel.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkWorkingLabel.setFont(font)
        self.checkWorkingLabel.setAutoFillBackground(True)
        self.checkWorkingLabel.setFrameShape(QtGui.QFrame.Box)
        self.checkWorkingLabel.setLineWidth(3)
        self.checkWorkingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkWorkingLabel.setObjectName(_fromUtf8("checkWorkingLabel"))
        self.verticalLayout_2.addWidget(self.checkWorkingLabel)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.queueControl = QtGui.QGroupBox(self.frame)
        self.queueControl.setObjectName(_fromUtf8("queueControl"))
        self.verticalLayout = QtGui.QVBoxLayout(self.queueControl)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.queueList = QtGui.QListWidget(self.queueControl)
        self.queueList.setObjectName(_fromUtf8("queueList"))
        self.verticalLayout.addWidget(self.queueList)
        self.queueLoad = QtGui.QPushButton(self.queueControl)
        self.queueLoad.setObjectName(_fromUtf8("queueLoad"))
        self.verticalLayout.addWidget(self.queueLoad)
        self.queueGo = QtGui.QPushButton(self.queueControl)
        self.queueGo.setObjectName(_fromUtf8("queueGo"))
        self.verticalLayout.addWidget(self.queueGo)
        self.queueStop = QtGui.QPushButton(self.queueControl)
        self.queueStop.setObjectName(_fromUtf8("queueStop"))
        self.verticalLayout.addWidget(self.queueStop)
        self.queueLoadPrev = QtGui.QPushButton(self.queueControl)
        self.queueLoadPrev.setObjectName(_fromUtf8("queueLoadPrev"))
        self.verticalLayout.addWidget(self.queueLoadPrev)
        self.queueAdd = QtGui.QPushButton(self.queueControl)
        self.queueAdd.setObjectName(_fromUtf8("queueAdd"))
        self.verticalLayout.addWidget(self.queueAdd)
        self.horizontalLayout.addWidget(self.queueControl)
        self.map = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setMinimumSize(QtCore.QSize(0, 0))
        self.map.setFrameShape(QtGui.QFrame.StyledPanel)
        self.map.setFrameShadow(QtGui.QFrame.Raised)
        self.map.setObjectName(_fromUtf8("map"))
        self.horizontalLayout.addWidget(self.map)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.eStopBox = QtGui.QGroupBox(self.frame_3)
        self.eStopBox.setObjectName(_fromUtf8("eStopBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.eStopBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.eStop1 = QtGui.QPushButton(self.eStopBox)
        self.eStop1.setObjectName(_fromUtf8("eStop1"))
        self.verticalLayout_3.addWidget(self.eStop1)
        self.eStop2 = QtGui.QPushButton(self.eStopBox)
        self.eStop2.setObjectName(_fromUtf8("eStop2"))
        self.verticalLayout_3.addWidget(self.eStop2)
        self.horizontalLayout_2.addWidget(self.eStopBox)
        self.groupBox_3 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.frame_4 = QtGui.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.timeLabel = QtGui.QLabel(self.frame_4)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.time = QtGui.QTimeEdit(self.frame_4)
        self.time.setReadOnly(True)
        self.time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.time.setObjectName(_fromUtf8("time"))
        self.horizontalLayout_3.addWidget(self.time)
        spacerItem1 = QtGui.QSpacerItem(7, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.timeLeftLabel = QtGui.QLabel(self.frame_4)
        self.timeLeftLabel.setObjectName(_fromUtf8("timeLeftLabel"))
        self.horizontalLayout_3.addWidget(self.timeLeftLabel)
        self.timeLeft = QtGui.QTimeEdit(self.frame_4)
        self.timeLeft.setReadOnly(True)
        self.timeLeft.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeLeft.setObjectName(_fromUtf8("timeLeft"))
        self.horizontalLayout_3.addWidget(self.timeLeft)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_DWG = QtGui.QAction(MainWindow)
        self.actionLoad_DWG.setObjectName(_fromUtf8("actionLoad_DWG"))
        self.actionLoad_DWG_2 = QtGui.QAction(MainWindow)
        self.actionLoad_DWG_2.setObjectName(_fromUtf8("actionLoad_DWG_2"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAhhhhh = QtGui.QAction(MainWindow)
        self.actionAhhhhh.setObjectName(_fromUtf8("actionAhhhhh"))
        self.menuFile.addAction(self.actionLoad_DWG)
        self.menuFile.addAction(self.actionLoad_DWG_2)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAhhhhh)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.checkWorkingLabel.setText(_translate("MainWindow", "Working", None))
        self.queueControl.setTitle(_translate("MainWindow", "Queue", None))
        self.queueLoad.setText(_translate("MainWindow", "Load Queue", None))
        self.queueGo.setText(_translate("MainWindow", "Go", None))
        self.queueStop.setText(_translate("MainWindow", "Stop", None))
        self.queueLoadPrev.setText(_translate("MainWindow", "Load Previous Queue", None))
        self.queueAdd.setText(_translate("MainWindow", "Add New Queue", None))
        self.eStopBox.setTitle(_translate("MainWindow", "E-Stops", None))
        self.eStop1.setText(_translate("MainWindow", "E-Stop 1", None))
        self.eStop2.setText(_translate("MainWindow", "E-Stop 2", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Progress", None))
        self.timeLabel.setText(_translate("MainWindow", "Time", None))
        self.time.setDisplayFormat(_translate("MainWindow", "mm:ss", None))
        self.timeLeftLabel.setText(_translate("MainWindow", "Time Left", None))
        self.timeLeft.setDisplayFormat(_translate("MainWindow", "mm:ss", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionLoad_DWG.setText(_translate("MainWindow", "Reset", None))
        self.actionLoad_DWG_2.setText(_translate("MainWindow", "Load DWG", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionAhhhhh.setText(_translate("MainWindow", "Ahhhhh", None))

